default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  user: postgres

development:
  <<: *default
  database: fridge_dev

test:
  <<: *default
  database: fridge_test

production:
  <<: *default
  database: fridge_prod
